=== a-ostrovsky/business_rules_kata/src/main/java/com/kata/businessrules/payment/userDefinedRules/xmlParsing/rules.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema targetNamespace="http://www.businessrules.com"
	xmlns:tns="http://www.businessrules.com" elementFormDefault="qualified"
	xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="actions">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="whenPaidFor" type="tns:whenPaidFor"
					minOccurs="0" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:complexType name="whenPaidFor">
		<xs:choice>
			<xs:element name="sendMessage" type="tns:sendMessage" />
			<xs:element name="receiptFor" type="tns:receiptFor" />
		</xs:choice>
		<xs:attribute name="productTitle" type="xs:string" use="optional" />
		<xs:attribute name="productType" type="xs:string" use="optional" />
	</xs:complexType>

	<xs:complexType name="sendMessage">
		<xs:sequence>
			<xs:element name="message" type="xs:string" minOccurs="1"
				maxOccurs="1" />
		</xs:sequence>
		<xs:attributeGroup ref="tns:receiverDescription" />
	</xs:complexType>

	<xs:complexType name="receiptFor">
		<xs:attribute name="product" type="tns:product" use="optional" />
		<xs:attribute name="productId" type="xs:string" use="optional" />
		<xs:attributeGroup ref="tns:receiverDescription" />
	</xs:complexType>

	<xs:attributeGroup name="receiverDescription">
		<xs:attribute name="receiver" type="tns:receiver" use="optional" />
		<xs:attribute name="receiverId" type="xs:string" use="optional" />
	</xs:attributeGroup>

	<xs:simpleType name="product">
		<xs:restriction base="xs:string">
			<xs:enumeration value="bought" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="receiver">
		<xs:restriction base="xs:string">
			<xs:enumeration value="customer" />
		</xs:restriction>
	</xs:simpleType>

</xs:schema>

=== a-ostrovsky/business_rules_kata/src/main/java/com/kata/businessrules/payment/userDefinedRules/xmlParsing/rules.xml
<?xml version="1.0" encoding="UTF-8"?>
<actions xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="rules.xsd">
	<whenPaidFor productTitle="Learning to Ski">
		<receiptFor productId="First_Aid_Id" receiver="customer" />
	</whenPaidFor>

	<whenPaidFor productType="Membership">
		<sendMessage receiver="customer">
			<message>Welcome...</message>
		</sendMessage>
	</whenPaidFor>

	<whenPaidFor productType="PhysicalProduct">
		<receiptFor product="bought" receiver="customer" />
	</whenPaidFor>

	<whenPaidFor productType="Book">
		<receiptFor product="bought" receiverId="royaltyDepartment" />
	</whenPaidFor>
</actions>
